### ISSUE TITLE
 [v0.4.5.5] Latest release does not correctly load libarary

### ISSUE THREAD

**Issue by KeaterCai** [bubblesub/pyffms2#33]
There is no problem with Installation. When loading libarary, some Problems occurs.

Mac OS X 10.13, Python 3.8
### Installation
ffms has been installed via homebrew
numpy has been installed.

### Here the Information

```
Python 3.8.10 (default, May  8 2021, 18:59:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ffms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/ffms2/__init__.py", line 33, in <module>
    from .libffms2 import *
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/ffms2/libffms2.py", line 9, in <module>
    lib = get_library(
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/ffms2/get_library.py", line 45, in get_library
    return load_library(
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/ffms2/get_library.py", line 167, in load_library
    return ctypes.CDLL(
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libffms2.dylib, 6): Symbol not found: _av_opt_set_int
  Referenced from: /usr/local/lib/libffms2.dylib
  Expected in: /usr/local/opt/ffmpeg/lib/libavformat.58.dylib
 in /usr/local/lib/libffms2.dylib
```

**Comment by KeaterCai** [comment]
That's my fault. 🤣, After updating ffms to latest version, this problem seem to be fixed.

**Comment by Luni-4** [comment]
No problem at all! 😄
